[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "crossing"
nine = "closed-contour"
a = "double-storey-serifless"
f = "flat-hook-serifless"
g = "double-storey"
i = "serifed"
k = "straight-serifless"
l = "serifed"
t = "flat-hook"
y = "straight-turn-serifless"
brace = "straight"
number-sign = "slanted"
at = "fourfold"
percent = "rings-continuous-slash"

[buildPlans.IosevkaCustom.variants.italic]
two = "straight-neck-serifless"
four = "closed-serifless"
six = "closed-contour"
eight = "crossing"
nine = "closed-contour"
f = "flat-hook-serifless"
g = "double-storey"
t = "flat-hook"
brace = "straight"
number-sign = "slanted"
percent = "rings-continuous-slash"

[buildPlans.IosevkaCustom.weights.Regular]
# Replace regular weight with medium
shape = 500
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaCustom.metricOverride]
# Replace usual 1250 height with 1200 so it's the same as Droid etc in mate-terminal
leading = 1200
